### ISSUE TITLE
I/Q stream by TCP connection? 

### ISSUE THREAD

**Issue by dg9bja** [szpajder/dumphfdl#10]
Hi,
I made some successful tests with I/Q data written by gnuradio. Needed gnuradio because there is no HPSDR support from SoapySDR.

Do you think it is possible to get this data through a simple TCP connection? Then there is no need to record to a file / stop recording / decoding / write new file. Then decoding would be like realtime receiption. 

Would be a great improvement!

**Comment by szpajder** [comment]
The current code from devel branch (https://github.com/szpajder/dumphfdl/tree/devel) allows reading I/Q samples from standard input. Specify --iq-file - to use this feature (that is, the file name should be a dash). If you need to feed the I/Q data over network, I suggest using netcat.

**Comment by szpajder** [comment]
I/Q input via pipe to stdin is now available in version 1.2.0.

No TCP input is planned at this time. I believe that Netcat + stdin pipe will do the job equally well.

Closing.
