### ISSUE TITLE
The devel "force AGC to disabled" for SDRPlay breaks --gain-elements for Airspy Mini

### ISSUE THREAD

**Issue by dlpwx** [szpajder/dumphfdl#26]
Doing some testing today I realized that [last week's force AGC to disabled devel branch commit](https://github.com/szpajder/dumphfdl/commit/2c0f73479d035f471d92697eb74012857fac266b) causes a problem with Airspy Mini devices. (When I thought I tested it last week I was actually still using a binary built from Master)

Tested on two Airspy Mini devices back and forth with Master and Devel binaries. With binaries built from devel, if I add `--gain-elements LNA=0,MIX=0,VGA=4` to dumphfdl config, the AGC (all gain) is off. There's no gain whatsoever until I remove `--gain-elements` and restart the dumphfdl instance. Using `--gain-elements` fine if I switch back to a dumphfdl binary built from Master. (Airspy autogain still works with devel binary as long as I don't use `--gain-elements`)

FYI - these older issues may be related to Airspy's soapy plugins instead of dumphfdl - unrelated to devel branch.

1. While --gain-elements works with Airspys, there's a small glitch. If I reboot with the --gain-elements flag in the dumphfdl config file (with dumphfdl as a systemd service to load at boot), the expected gain doesn't activate. It appears that the gain is really low, maybe AGC off. Simple work around is to remove --gain-elements before rebooting. Or just remove it after rebooting, restart dumphfdl, and re-add --gain-elements. Gain resumes as expected. (Oddly, after reboot, restarting dumphfdl service multiple times with --gain-elements still in the dumphfdl config doesn't work. I actually have to remove --gain-elments, then restart, then add it back in.). Perhaps I can test delaying service start after reboot, or adding some Wants or Wait-for-service in the systemd service config to see if this helps.
2. Another possible glitch, or possibly working as designed. Airspys will keep the same gain after I remove the --gain-elements flag and restart dumphfdl. Whatever the --gain-elements gain was set to before removing, is what I get after removing and restarting the dumphfdl instance. To reset autogain, the Airspy user must reboot without --gain-elements used in the config...
3. --gain-elements seems to have no effect with AirspyHF+ Discovery. Quick searching around made believe that this is because the SoapyAirspyHF plugin does not expose gain controls.

**Comment by szpajder** [comment]
> Tested on two Airspy Mini devices back and forth with Master and Devel binaries. With binaries built from devel, if I add --gain-elements LNA=0,MIX=0,VGA=4 to dumphfdl config, the AGC (all gain) is off. There's no gain whatsoever until I remove --gain-elements and restart the dumphfdl instance. 

So you've set the gain knobs manually to the lowest possible setting. "There's no gain whatsoever" seems to be the expected outcome then.

Crank it up to the max and see if it makes a difference. Here is a [chart with gain ranges for Airspy SDRs](https://discussions.flightaware.com/t/v5-0-5-airspy-dump1090-fa-with-native-airspy-support-now-available/78115/277).

**Comment by dlpwx** [comment]
> Crank it up to the max and see if it makes a difference.

Doh! You are correct. I didn't try going high enough since I also have some amplification in the chain. It does work if I use much higher gain (I already use the exact same chart you linked :-)). This also now works on AirspyHF+ Discovery as well.

So the question is what was happening previously with gain on Airspys? AGC maxed out? The current Master release still increases gain but starts out with a much higher gain. so VGA=4 was all I needed to get my min signal strength from say -89 dbfs to around -80. With current devel release `--gain-elements LNA=3,MIX=0,VGA=10` gives me about the same signal level as `--gain-elements LNA=0,MIX=0,VGA=4` did with the previous version. 

And now I can tune my AirspyHF+ as well!

**Comment by szpajder** [comment]
> So the question is what was happening previously with gain on Airspys? AGC
> maxed out?
>
As the current code in master doesn't explicitly turn off auto gain before
adjusting the gain manually, your --gain-elements setting probably didn't
work at all and the radio was just running on auto gain. Your "no gain
whatsoever" experience with LNA=0,MIX=0,VGA=4 suggests that right now your
settings actually do something.

I'll merge the fix into master and make a new release this week.

**Comment by szpajder** [comment]
Fix released in version 1.2.1
