### ISSUE TITLE
Add --station-id option like dumpvdl2

### ISSUE THREAD

**Issue by jaymot123** [szpajder/dumphfdl#29]
I'm feeding HFDL messages to a few aggregators including an under-development HFDL ingest that @kevinelliot is working on for airframes.io, and as his site aggregates messages from many ACARS and VDL feeders he'll need a way to tell who's sending him HFDL data. I'm feeding airframes.io JSON-formatted messages. It's basically for the same (or a similar) reason that's stated in the dumpvdl2 FAQ in its readme.

Thank you.

**Comment by szpajder** [comment]
It's there already. It's even mentioned in the usage text.

```
$ ./dumphfdl --help 2>&1 |grep station-id
    --station-id <string>                       Receiver site identifier
```
