### ISSUE TITLE
readStream failed: OVERFLOW, driver is uhd

### ISSUE THREAD

**Issue by adityadeva** [szpajder/dumphfdl#34]
![20230220_173049](https://user-images.githubusercontent.com/1020843/220100874-4b37a7d2-049b-4923-9c5c-854d1a2b16b4.jpg)

OSoapySDR device ' driver=uhd,': readStream failed: OWERFLOW

This message comes when using usrp b210. But RTLsdr works fine. 

Also there's no output when using dumphfdl versions (1.3 and 1.4). 1.2.0 is working fine with RTLsdr. However readStream failed message comes across all versions while using usrp ( driver=uhd)

**Comment by szpajder** [comment]
Please post the full command line which you use to run the program.

Does the OVERFLOW message appear just once on startup or it shows up
repeatedly, all the time?
