### ISSUE TITLE
Pipe Input?

### ISSUE THREAD

**Issue by M0CRT** [szpajder/dumphfdl#4]
Hi Szpajder

Awesome work here.  Was looking for this decoder within Linux for some time.

I've been using 'Kiwi_nc.py' to connect to a KiwiSDR to pipe streams from SDR over the network to an ICECast server using FFMPEG and the icecast output:

kiwi_nc.py --log=info -s <LOCAL IP OF KIWISDR> --user <USER> --password <PASS> -p 8073 -f 5515 -m usb | ffmpeg -v info -f s16le -ar 12000 -i pipe:0 -f ogg -content_type application/ogg icecast://source:<user>:<pass>@<ICECAST IP>/test.mp3

Any chance I can pipe from Kiwi_nc into dumphfdl to process audio from a KiwiSDR rather than from an IQ file or Soapy?  Be great to utilise any audio input.

Thanks

Mo

**Comment by szpajder** [comment]
Apparently kiwi_nc.py had a bug which caused I/Q samples to be handled incorrectly. I've submitted a patch and it has been accepted and now I'm getting good decodes with dumphfdl from Kiwis. Pull the current master branch from https://github.com/jks-prv/kiwiclient to get the fix.

**Comment by szpajder** [comment]
Released in version 1.2.0.

Closing.
