### ISSUE TITLE
fastddc_init function error while compiling

### ISSUE THREAD

**Issue by F4FYF** [szpajder/dumphfdl#41]
Hi
When i want to try compiling under debian 12 bookworm, i've got an error  

`[100%] Linking C executable dumphfdl
/usr/bin/ld : CMakeFiles/dumphfdl_base.dir/fastddc.o : dans la fonction « fastddc_init » :
fastddc.c:(.text+0x80) : référence indéfinie vers « is_integer »
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dumphfdl.dir/build.make:156 : dumphfdl] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:129 : CMakeFiles/dumphfdl.dir/all] Erreur 2
make: *** [Makefile:136 : all] Erreur 2
`
What can i do to pass that ? 

Thanks

Jeff

**Comment by szpajder** [comment]
I don't know, I can't reproduce this. I've just tested on Bookworm x86_64 and it built fine.
