### ISSUE TITLE
Incompatible with liquid-dsp 1.6.0

### ISSUE THREAD

**Issue by jrriss** [szpajder/dumphfdl#43]
When using liquid-dsp 1.6.0 on Archlinux no messages are decoded but after downgrading to liquid-dsp 1.5.0 it works as expected.

**Comment by szpajder** [comment]
Thanks for reporting this.

I've pushed a fix to the devel branch. Can you please try it out?

**Comment by jrriss** [comment]
Yes, that appears to be working.

**Comment by szpajder** [comment]
Fixed in version 1.6.1.
