### ISSUE TITLE
Short reads from stdin pipes causes premature termination

### ISSUE THREAD

**Issue by ka9q** [szpajder/dumphfdl#45]
When reading from a pipe being written by another process, the fread() library call can return a smaller amount than requested (but still greater than zero). This causes the do/while loop that starts at line 50 in input-file.c to exit prematurely, shutting down the input thread.

Changing line 64 from 
	} while(len == bufsize && do_exit == 0);
to
	} while(len > 0 && do_exit == 0);

keeps the loop going until an actual end-of-file (or error) is encountered on the input stream. With this change, I am successfully decoding HFDL traffic in real time from the output of a ka9q-radio receiver channel using this pipeline:

pcmrecord -v --ssrc 13276 --stdout kfs-omni-dynamic.local | dumphfdl --iq-file - --sample-rate 12000 --centerfreq 13276.0 --sample-format cs16 13276.0

The 'pcmrecord' command in my ka9q-radio package receives a signal stream from the specified multicast group and stream and sends it to standard output as PCM with a 'wav' header. It doesn't look like you process 'wav' headers, but they don't actually cause any harm. But if you did look at them I wouldn't have to specify the sample rate and format. I also put an extension in my wav header that gives the receiver center frequency, so that wouldn't need to be specified either.

**Comment by szpajder** [comment]
Hi Phil,

Thanks for reporting. I've merged your pull request into devel branch (this is where the new code goes first before it's merged into master and a release is made).

As far as WAV header goes - yup, it might be a valuable addition for this use case. I'll add this to my TODO list.

Regards and happy Christmas!
